CREATE TABLE Stack (
	StackID INT PRIMARY KEY IDENTITY (1, 1),
	NomeStack VARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE Flashcards (
	FlashcardsID INT PRIMARY KEY IDENTITY (1, 1),
	StackID INT NOT NULL,
	Front NVARCHAR(255) NOT NULL,
	Back NVARCHAR(255) NOT NULL,
	CONSTRAINT FK_Flashcards_stack
	FOREIGN KEY (StackID) REFERENCES dbo.Stack (StackID)
	ON DELETE CASCADE
);

CREATE TABLE StudySessions (
	SessionID INT PRIMARY KEY IDENTITY (1, 1),
	StackID INT NOT NULL,
	Date DATETIME NOT NULL DEFAULT GETDATE(),
	Score INT NOT NULL,
	CONSTRAINT FK_Studysessions_Stack
	FOREIGN KEY (StackID) REFERENCES dbo.Stack (StackID)
	ON DELETE CASCADE
);